spring:
  application:
    name: api-gateway

server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Clientes
        url: /clientes/api-docs
      - name: Ordenes
        url: /ordenes/api-docs
      - name: Eventos
        url: /eventos/api-docs
      - name: Recintos
        url: /recintos/api-docs
      - name: Exponentes
        url: /exponentes/api-docs
      - name: Precios
        url: /precios/api-docs
      - name: Tickets
        url: /tickets/api-docs
      - name: Resenas
        url: /resenas/api-docs